- type: job
  id: ServiceWorker
  name: job-name-serviceworker
  description: job-description-serviceworker
  playTimeTracker: JobServiceWorker
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 7200 # DeltaV - 2 hours
  startingGear: ServiceWorkerGear
  icon: "JobIconServiceWorker"
  supervisors: job-supervisors-service
  canBeAntag: true # DeltaV - Can be antagonist
  access:
  - Service
  - Maintenance
  extendedAccess:
  - Hydroponics
  - Bar # DeltaV - moved to extended access
  - Kitchen # DeltaV - moved to extended access

- type: startingGear
  id: ServiceWorkerGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: ServiceWorkerPDA
    ears: ClothingHeadsetService
